# Generated by Django 5.2.4 on 2025-07-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fixado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
