# Generated by Django 5.2.4 on 2025-07-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comment_fixado_alter_comment_criado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(max_length=40, unique=True)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
