# Generated by Django 5.2.4 on 2025-07-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_changelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default='1.0.0', max_length=20, verbose_name='Número da versão')),
                ('commit_hash', models.CharField(blank=True, max_length=40, null=True, verbose_name='Commit hash')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
