# Generated by Django 5.2.4 on 2025-07-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_versaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='exibir',
            field=models.BooleanField(default=True),
        ),
    ]
